export const CatalogLists = [
  { id: 1, text: "Aksiya", isActive: false },
  { id: 2, text: "Kompyuterlar va notebooklar", isActive: false },
  { id: 3, text: "Telefonlar", isActive: true },
  { id: 4, text: "Maishiy texnika", isActive: false },
  { id: 5, text: "Erkaklar uchun kiyim", isActive: false },
  { id: 6, text: "Ayollar uchun kiyimlar", isActive: false },
  { id: 7, text: "Bolalar uchun ", isActive: false },
  { id: 8, text: "Avtomobil mahsulotlari", isActive: false },
  { id: 9, text: "Go'zallik va so'glik", isActive: false },
  { id: 10, text: "Sport va o'yin-kulgi", isActive: false },
  { id: 11, text: "Uy hayvonlari uchun tovarlar", isActive: false },
  { id: 12, text: "Xobbi va ijodkorlik", isActive: false },
  { id: 13, text: "Kantselyariya buyumlari", isActive: false },
  { id: 15, text: "Sport va o'yin-kulgi", isActive: false },
  { id: 16, text: "Uy hayvonlari uchun tovarlar", isActive: false },
  { id: 17, text: "Aksesuarlar", isActive: false },
];
