import mac from "../assets/images/mac.png";
import img1 from "../assets/images/img1.png";
import img2 from "../assets/images/img2.png";
import img3 from "../assets/images/img3.png";
import img4 from "../assets/images/img4.png";
import filter1 from "../assets/images/filter1.png";
import filter2 from "../assets/images/filter2.png";
import filter3 from "../assets/images/filter3.png";
import filter4 from "../assets/images/filter4.png";
import filter5 from "../assets/images/filter5.png";
import filter6 from "../assets/images/filter6.png";
import filter7 from "../assets/images/filter7.png";
import filter8 from "../assets/images/filter8.png";
import filter9 from "../assets/images/filter9.png";
import filter10 from "../assets/images/filter10.png";
import filter11 from "../assets/images/filter11.png";
import filter12 from "../assets/images/filter12.png";
import filter13 from "../assets/images/filter13.png";

export const products = [
  {
    id: 1,
    title: `Apple Airpods Pro simsiz quloqchin , Oq rangda`,
    price: 299000,
    orders: 1230,
    image: mac,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 2,
    title: `Apple Airpods Pro simsiz quloqchin, Oq rangda`,
    price: 16114285,
    orders: 230,
    image: filter1,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: true,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 3,
    title: `Apple watch 4 `,
    price: 4234000,
    orders: 543,
    image: filter2,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 4,
    title: `Robot - tozalagich Xiaomi Mi Robot`,
    price: 1340000,
    orders: 876,
    image: filter3,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 5,
    title: `Oynali Fotoaparat Canon EOS 6D Body`,
    price: 1345000,
    orders: 566,
    image: filter4,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: true,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 6,
    title: `Apple Airpods Pro simsiz quloqchin , Oq rangda`,
    price: 299000,
    orders: 1230,
    image: filter5,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 7,
    title: `Apple Airpods Pro simsiz quloqchin, Oq rangda`,
    price: 16114285,
    orders: 230,
    image: filter6,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 8,
    title: `Apple watch 4 `,
    price: 4234000,
    orders: 543,
    image: filter7,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: true,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 9,
    title: `Robot - tozalagich Xiaomi Mi Robot`,
    price: 1340000,
    orders: 876,
    image: filter8,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 10,
    title: `Oynali Fotoaparat Canon EOS 6D Body`,
    price: 1345000,
    orders: 566,
    image: filter9,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: true,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 11,
    title: `Apple Airpods Pro simsiz quloqchin , Oq rangda`,
    price: 299000,
    orders: 1230,
    image: filter10,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 12,
    title: `Apple Airpods Pro simsiz quloqchin, Oq rangda`,
    price: 16114285,
    orders: 230,
    image: filter11,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 13,
    title: `Apple watch 4 `,
    price: 4234000,
    orders: 543,
    image: mac,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 14,
    title: `Robot - tozalagich Xiaomi Mi Robot`,
    price: 1340000,
    orders: 876,
    image: filter12,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 15,
    title: `Oynali Fotoaparat Canon EOS 6D Body`,
    price: 1345000,
    orders: 566,
    image: filter13,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: true,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 16,
    title: `Apple Macbook Pro 13" 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB  `,
    price: 16114285,
    orders: 230,
    image: filter3,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 17,
    title: `Apple Macbook Pro 13" 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB  `,
    price: 16114285,
    orders: 230,
    image: filter7,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 18,
    title: `Apple Macbook Pro 13" 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB  `,
    price: 16114285,
    orders: 230,
    image: filter10,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: true,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 19,
    title: `Apple Macbook Pro 13" 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB  `,
    price: 16114285,
    orders: 230,
    image: filter1,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: false,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
  {
    id: 20,
    title: `Apple Macbook Pro 13" 2.4 2019 Intel core i5 DDR3 8 GB SSD 256 GB  `,
    price: 16114285,
    orders: 230,
    image: filter13,
    numberOfMonth: [
      { id: 1, count: 3, isActive: true },
      { id: 2, count: 6, isActive: false },
      { id: 3, count: 12, isActive: false },
      { id: 4, count: 16, isActive: false },
      { id: 5, count: 18, isActive: false },
    ],
    images: [
      { id: 1, img: img1, selected: true },
      { id: 2, img: img2, selected: false },
      { id: 3, img: img3, selected: false },
      { id: 4, img: img4, selected: false },
    ],
    top_scale: true,
    new: false,
    colors: [
      { id: 1, color: "#BEBBC2", selected: true, text: "Space Gray" },
      { id: 2, color: "#F9DED7", selected: false, text: "Space Pink" },
      { id: 3, color: "#FCE9DB", selected: false, text: "Space Pink Light" },
      { id: 4, color: "#E8E8EA", selected: false, text: "Space Gray Light" },
    ],
  },
];
